/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.academico;
import java.util.*;
import javax.swing.JOptionPane;

/**
 *
 * @author SCIS2-27
 */
public class Ventanaprincipal extends javax.swing.JFrame {

   
    
    ArrayList<Integer> arraymenores = new ArrayList<>();
    ArrayList<Integer> arraymayores = new ArrayList<>();
    ArrayList<Integer> arrayadultos = new ArrayList<>();
    
    int sizeMenores;
    int sizeMayores;
    int sizeAdultos;
    
    public Ventanaprincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        create = new javax.swing.JButton();
        search = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SISTEMA ACADEMICO");

        create.setText("Crear");
        create.setEnabled(false);
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        search.setText("Consultar");
        search.setEnabled(false);
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        jButton1.setText("Tamaños");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(create)
                .addGap(54, 54, 54)
                .addComponent(search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(search)
                    .addComponent(jButton1))
                .addContainerGap(210, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
            int edad = 0;
            
            int i = 0;
            int i2 = 0;
            int i3 = 0;
            int i4 = 0;
            while(i<(sizeMenores+sizeMayores+sizeAdultos)){
                String texto = JOptionPane.showInputDialog(rootPane, "Diga su edad");
                for (int a = 0; a < texto.length(); a++) {
                    if (!Character.isDigit(texto.charAt(a))) {
                        edad = -1;
                        break;
                    }else{
                        edad = Integer.parseInt(texto);
                        
                    }
                }
                if(edad != -1){
                    if(edad>-1 && edad<18){
                        JOptionPane.showMessageDialog(rootPane,"Usted es MENOR de edad");
                        if(i2<sizeMenores){
                            arraymenores.add(edad);
                            i2++;

                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Menores Completados");
                            i--;
                        }
                    }else if(edad>=18 && edad < 60){
                        JOptionPane.showMessageDialog(rootPane, "Usted es MAYOR de edad");
                        if(i3<sizeMayores){
                            arraymayores.add(edad);
                            i3++;
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Mayores Completados");
                            i--;
                        }
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Usted es un ADULTO MAYOR");
                        if(i4<sizeAdultos){
                            arrayadultos.add(edad);
                            i4++;
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Adultos Mayores Completados");
                            i--;
                        }

                    }
                }else{
                    JOptionPane.showMessageDialog(rootPane, "ERROR: Números negativos o letras ingresadas");
                    i--;
                }
                
                
                i++;
        
            }
            search.setEnabled(true);
        
       
    }//GEN-LAST:event_createActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        
        JOptionPane.showMessageDialog(rootPane, "Menores: "+arraymenores.toString()+"\n"+"Mayores:"+arraymayores.toString()+"\n"+"Adultos Mayores: "+arrayadultos.toString());
    }//GEN-LAST:event_searchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        sizeMenores =  Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese cuantas personas quiere recibir de menores de edad"));
        sizeMayores =  Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese cuantas personas quiere recibir de mayores de edad"));
        sizeAdultos =  Integer.parseInt(JOptionPane.showInputDialog(rootPane, "Ingrese cuantas personas quiere recibir de adultos mayores"));
        
        create.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanaprincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanaprincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton create;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton search;
    // End of variables declaration//GEN-END:variables
}
